<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXK2YXe7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXK2YXe7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXK2YXe7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXK2YXe7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXK2YXe7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XK2YXe7',
    'container.build_id' => 'd094f98a',
    'container.build_time' => 1650747575,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXK2YXe7');
